export const DEVICE_MANAGER = 'DEVICE_MANAGER';
export const SCREENSHOT_MANAGER = 'SCREENSHOT_MANAGER';
export const USER_PREFERENCES = 'USER_PREFERENCES';
export const EXTENSIONS_MANAGER = 'EXTENSIONS_MANAGER';
