export const SCROLL_DOWN = 'SCROLL_DOWN';
export const SCROLL_UP = 'SCROLL_UP';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_RELOAD = 'NAVIGATION_RELOAD';
export const RELOAD_CSS = 'RELOAD_CSS';
export const ADDRESS_CHANGE = 'ADDRESS_CHANGE';
export const DELETE_STORAGE = 'DELETE_STORAGE';
export const SCREENSHOT_ALL_DEVICES = 'SCREENSHOT_ALL_DEVICES';
export const FLIP_ORIENTATION_ALL_DEVICES = 'FLIP_ORIENTATION_ALL_DEVICES';
export const TOGGLE_DEVICE_MUTED_STATE = 'TOGGLE_DEVICE_MUTED_STATE';
export const STOP_LOADING = 'STOP_LOADING';
export const APPLY_CSS = 'APPLY_CSS';

export const SET_NETWORK_TROTTLING_PROFILE = 'SET_NETWORK_TROTTLING_PROFILE';
export const CLEAR_NETWORK_CACHE = 'CLEAR_NETWORK_CACHE';
export const OPEN_CONSOLE_FOR_DEVICE = 'OPEN_CONSOLE_FOR_DEVICE';
export const PROXY_AUTH_ERROR = 'PROXY_AUTH_ERROR';

// status bar events
export const STATUS_BAR_VISIBILITY_CHANGE = 'status-bar-visibility-change';

export const HIDE_PERMISSION_POPUP_DUE_TO_RELOAD =
  'HIDE_PERMISSION_POPUP_DUE_TO_RELOAD';
export const PERMISSION_MANAGEMENT_PREFERENCE_CHANGED =
  'PERMISSION_MANAGEMENT_PREFERENCE_CHANGED';
export const START_MANAGEMENT_PREFERENCE_CHANGED =
  'START_MANAGEMENT_PREFERENCE_CHANGED';

export const TOGGLE_DEVICE_DESIGN_MODE_STATE =
  'TOGGLE_DEVICE_DESIGN_MODE_STATE';
