/* GENERATED by .erb/scripts/device-frames/generate.ts — edit sources.ts and regenerate. */
import type {FrameArtwork} from './geometry';
import nexus4 from './assets/nexus-4.webp';
import nexus5 from './assets/nexus-5.webp';
import nexus5x from './assets/nexus-5x.webp';
import nexus6 from './assets/nexus-6.webp';
import nexus6p from './assets/nexus-6p.webp';
import nexus7 from './assets/nexus-7.webp';
import nexus10 from './assets/nexus-10.webp';
import pixel2 from './assets/pixel-2.webp';
import pixel2Xl from './assets/pixel-2-xl.webp';
import pixel3 from './assets/pixel-3.webp';
import pixel3Xl from './assets/pixel-3-xl.webp';
import pixel4 from './assets/pixel-4.webp';
import pixel5 from './assets/pixel-5.webp';
import pixel7 from './assets/pixel-7.webp';
import pixel7a from './assets/pixel-7a.webp';
import pixel7Pro from './assets/pixel-7-pro.webp';
import pixel8 from './assets/pixel-8.webp';
import pixel8Pro from './assets/pixel-8-pro.webp';
import pixel8a from './assets/pixel-8a.webp';
import pixel9 from './assets/pixel-9.webp';
import pixel9Pro from './assets/pixel-9-pro.webp';
import pixel9a from './assets/pixel-9a.webp';
import pixel10 from './assets/pixel-10.webp';
import pixel10Pro from './assets/pixel-10-pro.webp';
import pixelTablet from './assets/pixel-tablet.webp';
import iphone5 from './assets/iphone-5.webp';
import iphone6 from './assets/iphone-6.webp';
import iphone6Plus from './assets/iphone-6-plus.webp';
import ipad from './assets/ipad.webp';
import motoG4 from './assets/moto-g4.webp';
import nestHub from './assets/nest-hub.webp';
import nestHubMax from './assets/nest-hub-max.webp';
import iphone4 from './assets/iphone-4.webp';
import iphoneSe2 from './assets/iphone-se-2.webp';
import iphoneX from './assets/iphone-x.webp';
import iphoneXr from './assets/iphone-xr.webp';
import iphone12Pro from './assets/iphone-12-pro.webp';
import iphone13Pro from './assets/iphone-13-pro.webp';
import iphone14 from './assets/iphone-14.webp';
import iphone14Pro from './assets/iphone-14-pro.webp';
import iphone15 from './assets/iphone-15.webp';
import iphone15Plus from './assets/iphone-15-plus.webp';
import iphone15Pro from './assets/iphone-15-pro.webp';
import iphone15ProMax from './assets/iphone-15-pro-max.webp';
import iphone16 from './assets/iphone-16.webp';
import iphone16Plus from './assets/iphone-16-plus.webp';
import iphone16Pro from './assets/iphone-16-pro.webp';
import iphone16ProMax from './assets/iphone-16-pro-max.webp';
import iphone17 from './assets/iphone-17.webp';
import iphone17Pro from './assets/iphone-17-pro.webp';
import iphone17ProMax from './assets/iphone-17-pro-max.webp';
import iphoneAir from './assets/iphone-air.webp';
import nothingPhone1 from './assets/nothing-phone-1.webp';
import laptop from './assets/laptop.webp';

/** Where a set of frame artwork comes from, for the attribution notice. */
export interface FrameSource {
  name: string;
  url: string;
  license: string;
  licenseUrl: string;
  copyright: string;
}

export const FRAME_SOURCES: Record<string, FrameSource> = {
  aosp: {
    name: 'Android Studio device art (AOSP)',
    url: 'https://android.googlesource.com/platform/tools/adt/idea/+/refs/heads/mirror-goog-studio-main/artwork/resources/device-art-resources/',
    license: 'Apache-2.0',
    licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0',
    copyright: 'Copyright (C) The Android Open Source Project',
  },
  'chrome-devtools': {
    name: 'Chrome DevTools device outlines',
    url: 'https://github.com/ChromeDevTools/devtools-frontend/tree/19e88ae6de83cc6dbb31f4c5c08209151c9b7b99/front_end/emulated_devices',
    license: 'BSD-3-Clause',
    licenseUrl:
      'https://github.com/ChromeDevTools/devtools-frontend/blob/19e88ae6de83cc6dbb31f4c5c08209151c9b7b99/LICENSE',
    copyright: 'Copyright 2014 The Chromium Authors',
  },
  'wikimedia-commons': {
    name: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org/wiki/Category:SVG_mobile_phones',
    license: 'per file (CC0 / CC BY 4.0 / CC BY-SA 4.0)',
    licenseUrl: 'https://creativecommons.org/licenses/',
    copyright: 'per file — see NOTICE.md',
  },
};

/** Every bundled frame, keyed by frame id. Credits: ./NOTICE.md. */
export const FRAME_ARTWORK = {
  'nexus-4': {
    src: nexus4,
    width: 1347,
    height: 2360,
    screen: {x: 132.19, y: 262.97, width: 1080, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-5': {
    src: nexus5,
    width: 1284,
    height: 2255,
    screen: {x: 135, y: 182.81, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-5x': {
    src: nexus5x,
    width: 1284,
    height: 2293,
    screen: {x: 137.81, y: 218.44, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-6': {
    src: nexus6,
    width: 1333,
    height: 2147,
    screen: {x: 161.02, y: 168.05, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-6p': {
    src: nexus6p,
    width: 1294,
    height: 2286,
    screen: {x: 137.11, y: 231.33, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-7': {
    src: nexus7,
    width: 1496,
    height: 2410,
    screen: {x: 182.81, y: 282.19, width: 1125, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'nexus-10': {
    src: nexus10,
    width: 1638,
    height: 2205,
    screen: {x: 257.34, y: 187.03, width: 1125, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-2': {
    src: pixel2,
    width: 1284,
    height: 2376,
    screen: {x: 131.25, y: 262.5, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-2-xl': {
    src: pixel2Xl,
    width: 1161,
    height: 2160,
    screen: {x: 125.63, y: 153.13, width: 900, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-3': {
    src: pixel3,
    width: 995,
    height: 2110,
    screen: {x: 45, y: 163.33, width: 900, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-3-xl': {
    src: pixel3Xl,
    width: 1024,
    height: 1974,
    screen: {x: 76.62, y: 43.78, width: 875.68, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-4': {
    src: pixel4,
    width: 930,
    height: 1972,
    screen: {x: 36.32, y: 115.26, width: 852.63, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-5': {
    src: pixel5,
    width: 932,
    height: 1903,
    screen: {x: 46.15, y: 50, width: 830.77, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-7': {
    src: pixel7,
    width: 900,
    height: 1906,
    screen: {x: 44.25, y: 43.5, width: 810, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-7a': {
    src: pixel7a,
    width: 920,
    height: 1919,
    screen: {x: 51.75, y: 51.75, width: 810, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-7-pro': {
    src: pixel7Pro,
    width: 892,
    height: 1888,
    screen: {x: 27.69, y: 38.08, width: 830.77, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-8': {
    src: pixel8,
    width: 890,
    height: 1885,
    screen: {x: 36.75, y: 41.25, width: 810, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-8-pro': {
    src: pixel8Pro,
    width: 884,
    height: 1867,
    screen: {x: 34.89, y: 34.89, width: 808.56, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-8a': {
    src: pixel8a,
    width: 899,
    height: 1904,
    screen: {x: 42.75, y: 42.75, width: 810, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-9': {
    src: pixel9,
    width: 890,
    height: 1879,
    screen: {x: 40.84, y: 43.07, width: 801.98, height: 1800},
    screenRadius: 64.6,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-9-pro': {
    src: pixel9Pro,
    width: 887,
    height: 1874,
    screen: {x: 37.82, y: 38.45, width: 806.72, height: 1800},
    screenRadius: 68.7,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-9a': {
    src: pixel9a,
    width: 909,
    height: 1908,
    screen: {x: 51.24, y: 54.21, width: 801.98, height: 1800},
    screenRadius: 64.6,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-10': {
    src: pixel10,
    width: 890,
    height: 1879,
    screen: {x: 43.81, y: 40.84, width: 801.98, height: 1800},
    screenRadius: 64.6,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-10-pro': {
    src: pixel10Pro,
    width: 887,
    height: 1869,
    screen: {x: 37.18, y: 37.82, width: 806.72, height: 1800},
    screenRadius: 62.39,
    orientation: 'portrait',
    source: 'aosp',
  },
  'pixel-tablet': {
    src: pixelTablet,
    width: 1967,
    height: 1292,
    screen: {x: 83.67, y: 82.27, width: 1800, height: 1125},
    screenRadius: 0,
    orientation: 'landscape',
    source: 'aosp',
  },
  'iphone-5': {
    src: iphone5,
    width: 1169,
    height: 2485,
    screen: {x: 90.63, y: 332.75, width: 1000.05, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'chrome-devtools',
  },
  'iphone-6': {
    src: iphone6,
    width: 1163,
    height: 2367,
    screen: {x: 75.56, y: 283.36, width: 1011.99, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'chrome-devtools',
  },
  'iphone-6-plus': {
    src: iphone6Plus,
    width: 1149,
    height: 2333,
    screen: {x: 63.59, y: 261.68, width: 1012.5, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'chrome-devtools',
  },
  ipad: {
    src: ipad,
    width: 1537,
    height: 2201,
    screen: {x: 91.33, y: 200.39, width: 1348.92, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'chrome-devtools',
  },
  'moto-g4': {
    src: motoG4,
    width: 1163,
    height: 2264,
    screen: {x: 83.1, y: 255.94, width: 997.15, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'chrome-devtools',
  },
  'nest-hub': {
    src: nestHub,
    width: 2090,
    height: 1575,
    screen: {x: 144.14, y: 130.08, width: 1800, height: 1054.69},
    screenRadius: 0,
    orientation: 'landscape',
    source: 'chrome-devtools',
  },
  'nest-hub-max': {
    src: nestHubMax,
    width: 2057,
    height: 1609,
    screen: {x: 129.38, y: 135, width: 1800, height: 1125},
    screenRadius: 0,
    orientation: 'landscape',
    source: 'chrome-devtools',
  },
  'iphone-4': {
    src: iphone4,
    width: 1454,
    height: 2746,
    screen: {x: 131.25, y: 480.75, width: 1200, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-se-2': {
    src: iphoneSe2,
    width: 1176,
    height: 2379,
    screen: {x: 79.47, y: 289.55, width: 1017.11, height: 1800},
    screenRadius: 0,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-x': {
    src: iphoneX,
    width: 957,
    height: 1919,
    screen: {x: 63.28, y: 59.26, width: 830.69, height: 1800},
    screenRadius: 86.38,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-xr': {
    src: iphoneXr,
    width: 957,
    height: 1919,
    screen: {x: 63.28, y: 59.26, width: 830.69, height: 1800},
    screenRadius: 86.38,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-12-pro': {
    src: iphone12Pro,
    width: 934,
    height: 1888,
    screen: {x: 50.84, y: 44, width: 831.07, height: 1800},
    screenRadius: 97.77,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-13-pro': {
    src: iphone13Pro,
    width: 934,
    height: 1888,
    screen: {x: 50.84, y: 44, width: 831.07, height: 1800},
    screenRadius: 97.77,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-14': {
    src: iphone14,
    width: 939,
    height: 1888,
    screen: {x: 53.78, y: 44, width: 831.07, height: 1800},
    screenRadius: 97.77,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-14-pro': {
    src: iphone14Pro,
    width: 929,
    height: 1884,
    screen: {x: 48.78, y: 41.95, width: 831.22, height: 1800},
    screenRadius: 117.07,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-15': {
    src: iphone15,
    width: 929,
    height: 1884,
    screen: {x: 48.78, y: 41.95, width: 831.22, height: 1800},
    screenRadius: 117.07,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-15-plus': {
    src: iphone15Plus,
    width: 919,
    height: 1876,
    screen: {x: 43.64, y: 38.3, width: 831.87, height: 1800},
    screenRadius: 115.78,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-15-pro': {
    src: iphone15Pro,
    width: 914,
    height: 1874,
    screen: {x: 39.78, y: 36.87, width: 834.5, height: 1800},
    screenRadius: 116.44,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-15-pro-max': {
    src: iphone15ProMax,
    width: 908,
    height: 1867,
    screen: {x: 36.95, y: 33.43, width: 833.14, height: 1800},
    screenRadius: 114.37,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-16': {
    src: iphone16,
    width: 929,
    height: 1884,
    screen: {x: 48.78, y: 41.95, width: 831.22, height: 1800},
    screenRadius: 117.07,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-16-plus': {
    src: iphone16Plus,
    width: 919,
    height: 1876,
    screen: {x: 43.64, y: 38.3, width: 831.87, height: 1800},
    screenRadius: 115.78,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-16-pro': {
    src: iphone16Pro,
    width: 907,
    height: 1860,
    screen: {x: 39.49, y: 29.86, width: 828.25, height: 1800},
    screenRadius: 115.57,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-16-pro-max': {
    src: iphone16ProMax,
    width: 905,
    height: 1860,
    screen: {x: 35.07, y: 29.81, width: 834.68, height: 1800},
    screenRadius: 113.98,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-17': {
    src: iphone17,
    width: 899,
    height: 1861,
    screen: {x: 35.98, y: 31.01, width: 827.43, height: 1800},
    screenRadius: 115.37,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-17-pro': {
    src: iphone17Pro,
    width: 899,
    height: 1861,
    screen: {x: 35.98, y: 31.01, width: 827.43, height: 1800},
    screenRadius: 115.37,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-17-pro-max': {
    src: iphone17ProMax,
    width: 899,
    height: 1857,
    screen: {x: 32.93, y: 28.39, width: 832.43, height: 1800},
    screenRadius: 113.56,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'iphone-air': {
    src: iphoneAir,
    width: 905,
    height: 1866,
    screen: {x: 39.47, y: 33.49, width: 825.25, height: 1800},
    screenRadius: 116.01,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  'nothing-phone-1': {
    src: nothingPhone1,
    width: 915,
    height: 1891,
    screen: {x: 43.63, y: 44.88, width: 825.21, height: 1800},
    screenRadius: 92.24,
    orientation: 'portrait',
    source: 'wikimedia-commons',
  },
  laptop: {
    src: laptop,
    width: 2359,
    height: 1365,
    screen: {x: 277.42, y: 88.73, width: 1800, height: 1129.57},
    screenRadius: 0,
    orientation: 'landscape',
    source: 'wikimedia-commons',
  },
} satisfies Record<string, FrameArtwork>;

export type FrameId = keyof typeof FRAME_ARTWORK;
