#!/bin/bash

echo "Publishing..."
yarn run publish-mac
echo "Publishing... Done"

echo "Linking current version in S3..."
aws s3 cp s3://responsively-updates/stable/ResponsivelyApp-`node -p "require('./package.json').version"`.dmg s3://responsively-updates/stable/ResponsivelyApp.dmg  --acl public-read
echo "Linking current version in S3... Done"

