#!/bin/bash

echo "Publishing..."
yarn run publish-linux
echo "Publishing... Done"

echo "Linking current version in S3..."
aws s3 cp s3://responsively-updates/stable/ResponsivelyApp-`node -p "require('./package.json').version"`.AppImage s3://responsively-updates/stable/ResponsivelyApp.AppImage  --acl public-read
echo "Linking current version in S3... Done"

