name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./desktop-app

    strategy:
      matrix:
        os: [macos-13]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: ${{ !env.ACT && 'npm' || '' }} # Disable cache for nektos/act
          cache-dependency-path: ./desktop-app/yarn.lock

      - name: Install and build
        run: |
          yarn install
          yarn run postinstall
          yarn run build

      - name: Bump version
        run: |
          cd release/app
          yarn version --preid beta --prerelease
          git push

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLEID }}
          APPLE_ID_PASS: ${{ secrets.APPLEIDPASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn exec electron-builder -- --publish always --win --mac --linux --arm64 --x64
